### ISSUE TITLE
npm install fails on fresh checkout

### ISSUE THREAD

**Issue by ptomasroos** [rendrjs/rendr-examples#2]
> rendr-example@0.0.0 postinstall /home/tomas/dev/node/rendr-examples/00_simple
> test -f ../../package.json && npm install ../../ || echo

npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.4 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-mocha@0.1.4 wants karma@>=0.12.8
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9

npm ERR! System Linux 3.11.0-19-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/tomas/dev/node/rendr-examples/00_simple
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tomas/dev/node/rendr-examples/00_simple/npm-debug.log
npm ERR! not ok code 0

**Comment by saponifi3d** [comment]
https://github.com/rendrjs/rendr-examples/pull/8 - should fix this. sorry I have been mostly making sure rendr is up to date not just the examples. I'm going through and upgrading each of the examples and will be adding another example that uses gulp + browserify.
