### ISSUE TITLE
RequireJS example doesn't work

### ISSUE THREAD

**Issue by iMoses** [rendrjs/rendr-examples#23]
It happens because this piece of code in injected into `common.js` and reaches the client.

```
// Create a simple path alias to allow browserify to resolve
// the runtime on a supported path.
module.exports = require('./dist/cjs/handlebars.runtime');
```

Error:
```
Uncaught ReferenceError: module is not defined(anonymous function) @ common.js:6658
```

**Comment by ingiulio** [comment]
@iMoses yes I get the same error. I can't figure out a solution right away, but I'll look into it. 
Thanks for bringing it up!

**Comment by crwang** [comment]
Closing this as it has been fixed.

**Comment by alexindigo** [comment]
Awesome. Thanks :)
