### ISSUE TITLE
Upgrade dependencies to the latest modules

### ISSUE THREAD

**Issue by roncli** [rendrjs/rendr-examples#6]
I currently have a fork at [roncli/rendr-examples](https://github.com/roncli/rendr-examples) that upgrades all of the modules to their latest versions.  This also fixes some outstanding issues reported by other users as well, as my goal was to get everything working, including the karma tests in examples 00 and 06.

However, three bugs are preventing me from actually creating a pull request for this:
* rendrjs/rendr#379 - This allows rendrjs to use express 4.
* joeybaker/remapify#7 (which depends on benbria/aliasify#13) - This fixes a bug on Windows and a security issue on all OSes related to browserify.
* (FIXED) lorenwest/node-config#123 - This fixes a bug related to empty YAML files being passed into node-config.

Once these three pull requests are accepted, I will create a pull request here that will upgrade the dependencies of the examples to all of the latest modules.

My code should also resolve #1, #2, and #3, and the pull request will supercede #4 and #5.  Of course, if you accept #4 and #5, I will merge those in to my code as well.

**Comment by saponifi3d** [comment]
thanks for this stuff! looks awesome. I am going to be going through upgrading all of the examples and adding another for gulp + browserify. The simple app is open for PR now (also uses rendr-handlebars 1.0.0 which has handlebars 2.0.0).

**Comment by crwang** [comment]
I'm going to close this as it's a year old now.
